'use strict';
(() => {
let snapshot={runs:[],tasks:[],agents:[],approvals:[],locks:[]},events=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const fmt=d=>d?new Date(d).toLocaleString():'—';
const cls=s=>['DONE','PASS','READY','APPROVED'].includes(s)?'ready':['FAILED','BLOCKED','CANCELLED','REJECTED'].includes(s)?'bad':['HUMAN_REQUIRED','WAITING','PAUSED'].includes(s)?'warn':'neutral';
async function refresh(){try{snapshot=await window.aecp.getControlPlaneStatus();events=await window.aecp.getControlPlaneEvents(300);if(document.body.dataset.aecpCommand==='1')render();}catch{}}
function render(){
 const host=document.querySelector('#controlContent');if(!host||document.body.dataset.aecpCommand!=='1')return;
 const runs=snapshot.runs||[],tasks=snapshot.tasks||[],apps=snapshot.approvals||[],running=runs.filter(x=>x.state==='RUNNING').length,queued=tasks.filter(x=>x.state==='QUEUED').length,waiting=apps.filter(x=>x.state==='WAITING').length,done=tasks.filter(x=>x.state==='DONE').length,total=tasks.length,pct=total?Math.round(done*100/total):0;
 let h='';
 h+='<div class="hc-shell"><div class="hc-toolbar"><div><span class="eyebrow">HARNESS COMMAND CENTER</span><h1>AI Engineering Team Control Plane</h1><p>Durable queue · scheduler · leases · recovery · approvals · event journal · multi-worker execution</p></div><div class="hc-toolbar-actions"><button class="secondary-button" id="hcRefresh">Refresh</button><button class="primary-button" id="hcEmergency">STOP ALL</button></div></div>';
 h+='<section class="hc-card hc-status-card"><div class="section-title"><h2>Implementation Status</h2><span class="status ready">SYNCED · 2026-09-19</span></div><div class="hc-status-grid"><div><b>CORE CONTROL PLANE</b><span class="status ready">IMPLEMENTED</span><small>Mission · Queue · Scheduler · Locks · Recovery</small></div><div><b>AI LOOP</b><span class="status ready">IMPLEMENTED</span><small>Planner · Builder · Verify · Reviewer · Rework</small></div><div><b>GITHUB / CI</b><span class="status ready">IMPLEMENTED</span><small>Branch · Draft PR · CI monitor · Rework</small></div><div><b>GOVERNANCE</b><span class="status warn">HARDENING</span><small>Policy · Evidence · Human merge gate</small></div><div><b>MULTI-REPO</b><span class="status ready">IMPLEMENTED</span><small>Repository discovery · task routing · per-repo locks</small></div><div><b>REMOTE</b><span class="status warn">LOCAL ONLY</span><small>Authenticated read-only loopback gateway; LAN/mobile remains gated</small></div></div><div class="hc-pending"><strong>Next completion gates:</strong> GitHub event receiver is implemented (opt-in) · local gateway is implemented · remaining: LAN pairing, full E2E matrix, production signing and Store distribution.</div></section>';h+='<div class="hc-metrics"><div><strong>'+running+'</strong><span>RUNNING</span></div><div><strong>'+queued+'</strong><span>QUEUED</span></div><div><strong>'+waiting+'</strong><span>APPROVAL</span></div><div><strong>'+done+'/'+total+'</strong><span>TASKS DONE</span></div><div><strong>'+pct+'%</strong><span>PROGRESS</span></div></div>';
 h+='<section class="hc-card hc-mission-create"><div class="section-title"><h2>New Mission</h2><span class="status safe">AUTONOMOUS / BOUNDED</span></div><div class="hc-form"><label>Goal<textarea id="hcGoal" rows="3" placeholder="例如：把 AECP Harness 做成可長時間自動施工、可恢復、可審計的工程控制平面。"></textarea></label><label>Definition of Done<textarea id="hcDone" rows="3" placeholder="列出完成條件、測試、CI、證據與人工批准條件。"></textarea></label><div class="hc-inline"><label>Concurrency<input id="hcConcurrency" type="number" min="1" max="8" value="2"></label><label>Max iterations<input id="hcIterations" type="number" min="1" max="5" value="5"></label><label>Max tasks<input id="hcTasks" type="number" min="1" max="8" value="8"></label><label class="hc-check"><input id="hcDelivery" type="checkbox"> Governed GitHub draft PR</label><button class="primary-button hc-create" id="hcCreate">START MISSION</button></div></div></section>';
 h+='<div class="hc-grid"><section class="hc-card"><div class="section-title"><h2>Mission Queue</h2><span class="count-badge">'+runs.length+'</span></div><div class="hc-table">';
 h+=runs.length?runs.map(r=>{let a='';if(r.state==='PAUSED')a+='<button data-start="'+esc(r.id)+'" class="secondary-button">Resume</button>';if(['QUEUED','RUNNING','PAUSED','HUMAN_REQUIRED'].includes(r.state))a+='<button data-pause="'+esc(r.id)+'" class="secondary-button">Pause</button>';if(!['DONE','BLOCKED','FAILED','CANCELLED'].includes(r.state))a+='<button data-cancel="'+esc(r.id)+'" class="secondary-button">Cancel</button>';return '<div class="hc-row"><div class="hc-main"><strong>'+esc(r.goal)+'</strong><small>'+esc(r.id)+' · '+fmt(r.createdAt)+'</small></div><span class="status '+cls(r.state)+'">'+esc(r.state)+'</span><div class="hc-actions">'+a+'</div></div>';}).join(''):'<div class="empty-list">No missions yet.</div>';
 h+='</div></section><section class="hc-card"><div class="section-title"><h2>Approval Queue</h2><span class="count-badge">'+waiting+'</span></div><div class="hc-table">';
 h+=apps.filter(a=>a.state==='WAITING').map(a=>'<div class="hc-row hc-approval"><div class="hc-main"><strong>'+esc(a.reason)+'</strong><small>'+esc(a.taskId)+' · Risk '+esc(a.risk)+' · '+fmt(a.createdAt)+'</small></div><div class="hc-actions"><button data-approve="'+esc(a.id)+'" class="primary-button">Approve</button><button data-reject="'+esc(a.id)+'" class="secondary-button">Reject</button></div></div>').join('')||'<div class="empty-list">No human approvals waiting.</div>';
 h+='</div></section></div><section class="hc-card"><div class="section-title"><h2>Task Board</h2><span class="count-badge">'+tasks.length+'</span></div><div class="hc-task-grid">';
 h+=tasks.map(t=>'<article class="hc-task"><div class="hc-task-head"><strong>'+esc(t.title)+'</strong><span class="status '+cls(t.state)+'">'+esc(t.state)+'</span></div><p>'+esc(t.objective||t.acceptance||'')+'</p><small>'+esc(t.id)+' · attempt '+(t.attempts||0)+' · heartbeat '+fmt(t.heartbeatAt||t.updatedAt)+'</small>'+(t.delivery?.pr?'<div class="hc-actions"><span>PR '+esc(t.delivery.pr)+'</span>'+(t.delivery.state==='DRAFT'?'<button data-merge="1" data-run="'+esc(t.runId)+'" data-task="'+esc(t.id)+'" class="primary-button">Approve & Merge</button>':'')+'</div>':'')+(t.ci?'<small>CI: '+esc(t.ci.state)+'</small>':'')+(t.error?'<pre>'+esc(t.error)+'</pre>':'')+'</article>').join('')||'<div class="empty-list">Queue is empty.</div>';
 h+='</div></section><section class="hc-card"><div class="section-title"><h2>Live Event Stream</h2><span class="status ready">JOURNALED</span></div><div class="hc-events">';
 h+=events.slice().reverse().slice(0,120).map(e=>'<div class="hc-event"><time>'+esc(fmt(e.at))+'</time><b>'+esc(e.type)+'</b><span>'+esc(e.runId||'')+'</span><span>'+esc(e.taskId||'')+'</span></div>').join('')||'<div class="empty-list">No events yet.</div>';
 h+='</div></section></div>';host.innerHTML=h;
 document.querySelector('#hcRefresh')?.addEventListener('click',refresh);
 document.querySelector('#hcEmergency')?.addEventListener('click',async()=>{if(!confirm('STOP ALL will cancel every active mission. Continue?'))return;for(const r of runs.filter(x=>['QUEUED','RUNNING','PAUSED','HUMAN_REQUIRED'].includes(x.state)))await window.aecp.cancelMission(r.id);await refresh();});
 document.querySelector('#hcCreate')?.addEventListener('click',async()=>{const goal=document.querySelector('#hcGoal').value.trim(),done=document.querySelector('#hcDone').value.trim();if(!goal||!done){alert('Goal and Definition of Done are required.');return;}await window.aecp.createMission({goal,done,maxConcurrency:Number(document.querySelector('#hcConcurrency').value),maxIterations:Number(document.querySelector('#hcIterations').value),maxTasks:Number(document.querySelector('#hcTasks').value),delivery:document.querySelector('#hcDelivery').checked,autoStart:true});await refresh();});
 document.querySelectorAll('[data-start]').forEach(b=>b.onclick=async()=>{await window.aecp.startMission(b.dataset.start);await refresh();});document.querySelectorAll('[data-pause]').forEach(b=>b.onclick=async()=>{await window.aecp.pauseMission(b.dataset.pause);await refresh();});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await window.aecp.cancelMission(b.dataset.cancel);await refresh();});document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{await window.aecp.approveMissionAction(b.dataset.approve);await refresh();});
 document.querySelectorAll('[data-merge]').forEach(b=>b.onclick=async()=>{if(!confirm('Merge this governed PR into main?'))return;await window.aecp.approveDelivery({runId:b.dataset.run,taskId:b.dataset.task,by:'human'});await refresh();});document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{await window.aecp.rejectMissionAction(b.dataset.reject);await refresh();});
}
function activate(){document.body.dataset.aecpCommand='1';document.querySelectorAll('.view-tab').forEach(x=>x.classList.toggle('active',x.dataset.view==='command'));const t=document.querySelector('#controlTitle');if(t)t.textContent='Harness Command Center';refresh();}
function deactivate(){document.body.dataset.aecpCommand='0';}
document.addEventListener('click',e=>{const tab=e.target.closest('.view-tab');if(tab?.dataset.view==='command')setTimeout(activate,0);else if(tab&&tab.dataset.view!=='command')deactivate();},true);
window.aecp.onControlPlaneEvent(refresh);refresh();setInterval(refresh,3000);
})();
const HARDENING_GATES = ['Failure Recovery Assistant — bounded classifier implemented','Adapter Security Audit','Clean E2E Matrix','Windows Release Gate','Authenticated Remote Pairing','Drift Scans'];
